config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'

  resources :users

  resources :sessions

  get 'signup',  to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout',  to: 'sessions#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :name, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 4}
  validates :instructions, presence: true
  validates :ingredients, presence: true
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300.", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :email, presence: true
  validates :email, uniqueness: true

   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment].permit(:name, :body))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.js   { }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @ingredients = @post.ingredients.split("-")
    @instructions = @post.instructions.split("-")
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :ingredients, :instructions, :cook_time, :original_recipe, :image))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :ingredients, :instructions, :cook_time, :original_recipe)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    p params
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      log_in @user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorize
    redirect_to login_url if current_user.nil?
  end

  def admin?
    current_user.id == 1
  end

end

app/views/comments/_comment.html.erb
  <p class='comment-body'><%= comment.body %></p>
  <p class='commenter'>-<%= comment.name %></p>
  <p class='time'><%= time_ago_in_words(comment.created_at) %> ago
  <% if logged_in? && admin? %>
    | <%= link_to 'Delete', [comment.post, comment], method: :delete %></p>
  <% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build], :remote => true do |f| %>
  <p>
      <%= f.label :name%>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :body%>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/comments/create.js.erb
console.log("create.js.erb file");

# add new comment to end of comments section
$(".comments").append("<%= @comment.name %>: <%= @comment.body %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>


    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul class='nav'>
        <li> <%= link_to "Home", root_path %> </li>
        <li> | </li>
        <li> <%= link_to "About", about_path %> </li>
        <li> | </li>
        <% if logged_in? %>
          <li><%= link_to "Logout", session_path('id'), method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_session_path %></li>
          <li> | </li>
          <li> <%= link_to "Sign Up", new_user_path %> </li>
        <% end %>
      </ul>
    </nav>
    <h1>Nicole's Favorite Recipes</h1>
    <% flash.each do |name, message|%>
      <%= content_tag(:div, message, class: 'alert') %>
    <% end %>
    <% if current_page?(root_path) && logged_in? && admin? %>
      <button id='new-post'><%= link_to "New Recipe", new_post_path %></button>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class='about-page'>
<h2>Hi, I'm Nicole!</h2>
  <p class='about'>I love cooking and I am always trying to find new recipes (especially crockpot recipes). I often find great recipes on various blogs but then have a hard time finding them again. Here is a collection of all my favorite recipes (from other blogs, and my family and friends). If the recipe is from another site, the link to the original is listed. Hope you enjoy!</p>
</div>

app/views/posts/_form.html.erb
<div class='new-recipe'>
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
    <%= f.label :image %>:
    <%= f.file_field :image %>
  </p>
 <p>
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :cook_time %>:
    <%= f.text_field :cook_time %>
  </p>
  <p>
    <%= f.label :ingredients %>:
    <%= f.text_area :ingredients, size: "30x10" %>
  </p>
  <p>
    <%= f.label :instructions %>:
    <%= f.text_area :instructions, size: "30x10" %>
  </p>
  <p>
    <%= f.label :original_recipe %>:
    <%= f.text_field :original_recipe %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Recipe</h2>
<%= render 'form'%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class='post-show'>
  <div class='thumb-pic'>
    <%= image_tag post.image.url(:thumb) %>
  </div>
  <h2 class='show-title'> <%= link_to post.title, post %> </h2>
  <p class='show-created'><%= post.created_at.strftime("%B %d, %Y") %></p>
  </div>
 <% end %>

app/views/posts/new.html.erb
<h2>New Recipe</h2>
<%= render 'form'%>

app/views/posts/show.html.erb
<div class='entire-recipe'>
<h2 class='recipe-title'><%= @post.title %></h2>

<p class="date">
  Created <%= time_ago_in_words(@post.created_at) %> ago.
  <% if logged_in? && admin? %>|
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure you would like to delete this post?'} %>
    <% end %>
</p>

<div class="body">
  <%= image_tag @post.image.url(:large) %>
  <h4>Cook time: <%= @post.cook_time %></h4>
  <h3>Ingredients</h3>
  <div class='ingredients'>
  <ul>
    <% @ingredients.each do |ingredient| %>
      <li><%= ingredient %></li>
    <% end %>
    </ul>
    </div>
  <h3>Instructions</h3>
  <div class="instructions">
     <ol>
    <% @instructions.each do |instruction| %>
      <li><%= instruction %></li>
    <% end %>
    </ol>
    </div>
    <p><%= link_to 'Original Recipe', @post.original_recipe %></p>
</div>
<div class='comments'>
  <h3>Comments</h3>
  <%= render @post.comments %>
  <% if logged_in? %>
    <h4>Add a Comment</h4>
    <%= render 'comments/form' %>
  <% end %>
</div>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<% if @errors %>
  <% @errors.each do |error| %>
  <p><%= error %></p>
  <% end %>
<% end %>
<%= form_for @user do |f| %>
 <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
   <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>